# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b76ed928c5b6071d5328c05bbc248a0dc817fd7e651ec0910b182b5e3857399079c8f76242975441b922a1a9fd6dff414361f3147eb15424d3df7dd3b031cce4

test:
  secret_key_base: 86a74c5ba6aac59c9b61334b3c10ba4d2d8f0660f8bb22de7bc8abeb7d992ecb887c4a3c3ecb1a9ef25b3b55b9744bece5c669f3a08bc902ff5aa3cd385a8ff1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
