default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: movies_has_many_development

test:
  <<: *default
  database: movies_has_many_test

production:
  <<: *default
  database: movies_has_many_production
  username: movies_crud_app
  password: <%= ENV['MOVIES_HAS_MANY_DATABASE_PASSWORD'] %>
