development:
  adapter: postgresql
  encoding: unicode
  database: wdi_6_rails_lab_feature_spec_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: wdi_6_rails_lab_feature_spec_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: wdi_6_rails_lab_feature_spec_production
  pool: 5
