# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3245c25c6e6e0c15172b1f8477bb068aab4864b2457f5e789f7ae611109dc0d489b6d3cd9a375286f6e297387e827a8bd6c16ef039257347f4c4dbb52bbbfd3

test:
  secret_key_base: 1fb99284198a5f64c1feeb82e9e6d3f8eadc0e943cd0d5449a05ae60140d8b272a95531f304c0f116016840d360f83a591a04b5260ab27c374216d5d18e2359b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
