# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26df32ec24c7cad773d1aca4ff638aeb46c6faae1d84967a23ad8e6425855f6bd9d893681393fd13338664ebdc2b2e56dedda30f35e3b1af818426d0c635f4dd

test:
  secret_key_base: 2aaa845ebd8f6beca7447672cd1938f294f24b7d955d39e6c798a12d0a1a55eade30f0af1a021824a7e3e3b00c1df4e1f7430795f43b0f96b87053e8fbb6c018

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
