
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: polymorphic_example_development
  pool: 5

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: polymorphic_example_test
  pool: 5

