development:
  adapter: postgresql
  encoding: unicode
  database: TestingContactManager_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: TestingContactManager_test
  pool: 5
