# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b5a1faccc2269a6799605c05cc5c89ce6042ec588b181c35e6de6f65130d28232bc6e01927d6add8bbe7455df34a78afa9609fdd09385f3b6a1ffe786a0c750

test:
  secret_key_base: 23aac396d9a3141d8462c8d8079677295da5351e4ac3edfec415084b249ff71c0b128acaa37cf9d035a09af4a47c1f6981f4498eca9e9be2e59961c4d14121ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
