development:
  adapter: postgresql
  encoding: unicode
  database: BooksAppWithMailer_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: BooksAppWithMailer_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: BooksAppWithMailer_production
  pool: 5
