# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dea693635458a5fb6735babbd5756a69c1f601d6c1d6ead75dceef88e54c4534c14e9956ea5f1a0ba2fa82dae141a9fd89094a47a4de28010b18c08229a3d779

test:
  secret_key_base: e1ab6c177523089a72ebe8ef24754e4edb3e2cca3012293f8bb18d5820cb122ddfa9a19e1049bbe17c036e849d4a56de77012a8f012dcedc9007b6f474d6a566

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
