# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 022b113e54bce902352ed41e33ebc51a69adbc5bb362691133f62f1f126fec90565fbb9adadeb8d4829f68d896373853341db8ba4d3ce81f9745800470266aff

test:
  secret_key_base: d9020b4c22512a48338f64b5edb73e849948a453fe6dc0e7866ed4e9d965df605f37a512019417c8537c99b92f3b4b74af8d4bb9c6c4d8f8394b6f422d238b25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
