development:
  adapter: postgresql
  encoding: unicode
  database: articles_api_development

test:
  adapter: postgresql
  encoding: unicode
  database: articles_api_test

production:
  adapter: postgresql
  encoding: unicode
  database: articles_api_production
