# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bce70997f0be83a139948cbefe7a11c5883fa0b66993943a94891bea80b8d2dbe296aa6fe240e4c38116f2f1c02592c0c98936f1da6479f7e69c1131311172d

test:
  secret_key_base: b259d41a36cc8354b642d181db496b789fd0fc6d54fde52efe5fef2901803fdaffffa62def436b6fff59127cb43a5b406fc6bfec2ad2e21547d5d9f74a26d171

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
