# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 384abc25d7169cb55463f0dcba1d625c8c304c41195bb5827e405ae64e78893a78e68a86e36a5c44d2b0af44c0acba577d4e1a4f65b3cbd98ffab6d8e74bafa0

test:
  secret_key_base: 469d1f570b02500f22aec8d3914cd6e93a03f946d50266cfdab46aca9d12e8439fccd8a4b3b218917edcadda1313b8aabca12f231b6eb88d749550f97ccb6846

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
