development:
  adapter: postgresql
  encoding: unicode
  database: ProductFront_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ProductFront_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ProductFront_production
  pool: 5
