development:
  adapter: postgresql
  encoding: unicode
  database: wdi_6_rails_demo_newrelic_development

test:
  adapter: postgresql
  encoding: unicode
  database: wdi_6_rails_demo_newrelic_test

production:
  adapter: postgresql
  encoding: unicode
  database: wdi_6_rails_demo_newrelic_production
