development:
  adapter: postgresql
  encoding: unicode
  database: wdi_4_rails_lab_routes_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: wdi_4_rails_lab_routes_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: wdi_4_rails_lab_routes_production
  pool: 5
