---

- name: Upload locale settings
  copy: dest=/etc/profile.d/lang.sh src=lang.sh

- name: Source locale settings
  script: lang.sh

- name: Upgrade packages
  apt: upgrade=full update_cache=yes force=yes

- name: Install required packages
  apt: pkg={{ item }} state=present
  with_items:
    - aptitude
    - unattended-upgrades
    - zsh
    - build-essential
    - mailutils
    - git
    - ruby
    - node

- name: Adjust APT update intervals
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Make sure unattended-upgrades only installs from $ubuntu_release-security
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent
