---

- name: Source locale settings
  script: lang.sh

- name: Add postgres repository
  template: src=pgdg.list.j2 dest=/etc/apt/sources.list.d/pgdg.list

- name: Add postgres repository key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present

- name: Install postgresql-$postgres_version
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
  - postgresql-{{ postgres_version }}
  - libpq-dev
  when: skip_packages is not defined

- name: Enable db authentication over shell
  lineinfile: dest=/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf regexp="^local.*all.*postgres" line="local   all             postgres                                 md5" state=present
  notify: Restart postgresql
