# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 971833ac4c6a812d0bfefac7d68a302bfefec24d5264fbdbb93b27cd2216d706018b5e6d5e19f823e5d5fb0b33824713511366122d9bde4d7eb8ca9d1f43cd57

test:
  secret_key_base: c44aff6f5179b1547881836b9f02dde61f178239b994f7bad43af64744aa6903d05a9e74c53a92e6e4115ccc590fa40213d89fb4e936ddbc632f057f04ebe2c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
