# Generated by Django 3.1.1 on 2020-09-01 13:03

from django.db import migrations

def seed(apps, schema_editor):
    Song = apps.get_model('tunr', 'Song')
    Artist = apps.get_model('tunr', 'Artist')
    beatles = Artist(name="Beatles", nationality="British", photo_url="https://images.daznservices.com/di/library/GOAL/85/c5/the-beatles_2z8f20c4ubfh1i0f0ye5po9xv.png?t=720966505&quality=60&w=1200&h=800")
    beatles.save()
    queen = Artist(name="Queen", nationality="British", photo_url="https://www.udiscovermusic.com/wp-content/uploads/2018/08/GH008-web-optimised-1000.jpg")
    queen.save()

    Song(artist = beatles, title='Hey Jude', album='Hey Jude', preview_url='https://images-na.ssl-images-amazon.com/images/I/81G5MhpJXuL._SL1500_.jpg').save()
    Song(artist = beatles, title='Here Comes the Sun', album='Abbey Road', preview_url='https://f4.bcbits.com/img/a3542281899_10.jpg').save()
    Song(artist = beatles, title='Twist and Shout', album='Please Please Me', preview_url='https://www.rockcellarmagazine.com/wp-content/uploads/2020/07/beatles-twist-and-shout-ep.jpg').save()
    Song(artist = queen, title='Don\'t Stop Me Now', album='Jazz', preview_url='https://lh3.googleusercontent.com/proxy/GP0TYajrVBIzZo_fMdik3Vyu8HnNl-VuAakIHa8SOiibBvdXPBmXAWCmYbD7y-8saqYR7d9gSpqvZ1HXPgVy83XZ-8VF2h6TF0yuc-sIaCv6gdPMH3uJZaqcjVmZFxdJd3F7y1811EliLw').save()
    Song(artist = queen, title='We Are the Champions', album='News of the World', preview_url='https://www.relevantrecordcafe.co.uk/wp-content/uploads/2016/09/Q-0016.jpg').save()


def fallow(apps, schema_editor):
    Song = apps.get_model('tunr', 'Song')
    Artist = apps.get_model('tunr', 'Artist')
    Artist.objects.all().delete()
    Song.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_auto_20200827_1912'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
