language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
before_install:
  - gem update --system 2.1.11
  - git config --global user.email 'user@example.com'
  - git config --global user.name 'Test User'
