# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # list of images: https://circleci.com/docs/2.0/circleci-images/
      # specify the version you desire here
      - image: circleci/node:8.11-stretch-browsers
      # need this to connect to mongodb
      - image: circleci/mongo:3.6-jessie-ram
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          command: 'npm install'
          name: Install npm packages

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: 
          command: 'npm test'
          name: Run tests


